[Variables]
RSS1=https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml
RSS1Name=New York Times
RSS2=http://rss.dw.com/rdf/rss-en-all
RSS2Name=DW
RSS3=http://feeds.bbci.co.uk/news/rss.xml?edition=int
RSS3Name=BBC
RSS4=http://rss.cnn.com/rss/edition.rss
RSS4Name=CNN News
RSS5=http://www.engadget.com/rss.xml
RSS5Name=Engadget
RSSMain=http://feeds.bbci.co.uk/news/rss.xml?edition=int
RSSMainName=BBC

IcoStyle=rss