[Variables]
App1Icon=1.png
App1Name=YouTube
App1Location=https://youtube.com

App2Icon=2.png
App2Name=DeviantART
App2Location=https://deviantart.com

App3Icon=3.png
App3Name=Facebook
App3Location=https://facebook.com

App4Icon=4.png
App4Name=Twitter
App4Location=https://twitter.com

App5Icon=5.png
App5Name=Reddit
App5Location=https://reddit.com


App6Icon=6.png
App6Name=Digg
App6Location=https://digg.com


App7Icon=7.png
App7Name=Episode Calendar
App7Location=https://episodecalendar.com/en/calendar
