[Variables]
langcode=en-us
Settings=Settings
Search=Search
Alternative=Alternative
Close=Close
AddItems=Add Items
Quit=Quit
MoreActions=More Actions...
Greetings=Greetings
GoodMorning=Good morning
GoodAfternoon=Good afternoon
GoodEvening=Good evening
AddAnother=Add Another


Today=Today
Calendar=Calendar
Moon=Moon
System=System
Greeter=Greeter
WorldClock=World Clock
Library=Library
Remote=Remote
NotesText=Notes
Photos=Photos
Timer=Timer
Weather=Weather
DigitalClock=Digital Clock
WMP=WMP
Tasks=Tasks
Battery=Battery
Clock=Clock
CPUMeter=CPU Meter
Greeter=Greeter
HDDMeter=HDD Meter
Launcher=Launcher
MediaCenter=Media Center
MediaControl=Media Control
Network=Network
Notes=Notes
Quotes=Quotes
RAMMeter=RAM Meter
RecycleBin=Recycle Bin
NewsReader=News Reader
Search=Search
Shortcuts=Shortcuts
Slideshow=Slideshow
TaskList=Task List
Uptime=Uptime
User=User
Visualizer=Visualizer
Weather=Weather
WMPControl=WMP Control
WorldClock=World Clock
SearchFor=Search for...
Storage=Storage
Sunrise=Sunrise
Used=Used
;Used 100GB


ItsMorning=It's morning in

ItsDay=It's day in
ItsEvening=It's evening in
itsnightin=It's night in
;It's midnight in Paris

Wallpapers=Wallpapers
NotesRename=Notes
TimeZoneClock=Add a Timezone Clock
CopyToClipboard=Copy to Clipboard
EmptyRecycleBin=Empty Recycle Bin

Items=Items
MON=Mon
Tue=Tue
Wed=Wed
Thu=Thu
Fri=Fri
Sat=Sat
Sun=Sun


Videos=Videos
TV=TV
Music=Music
Photos=Photos
WindowsMediaPlayer=Windows Media Player
NoPlayback=No playback


Hibernate=Hibernate
Shutdown=Shutdown
Restart=Restart
LogOff=Log Off
Lock=Lock
Sleep=Sleep


FinishTask=Finish Task
ClearTasksStatus=Clear Status
ClearTasks=Clear Tasks

AddAnotherHDD=Add Another Disk
AlignSidebarLeft=Align Sidebar to the Left
AlignSidebarRight=Align Sidebar to the Right
Welcome=Welcome